**Data Acquisition**

In [1]:
import pandas as pd

df = pd.read_csv('/content/NFHS_DATASET.csv')

if(not df.empty):
  print('Dataframe Created')
print(df.columns)

Dataframe Created
Index(['District Names', 'State/UT', 'Number of Households surveyed',
       'Number of Women age 15-49 years interviewed',
       'Number of Men age 15-54 years interviewed',
       'Female population age 6 years and above who ever attended school (%)',
       'Population below age 15 years (%)',
       ' Sex ratio of the total population (females per 1,000 males)',
       'Sex ratio at birth for children born in the last five years (females per 1,000 males)',
       'Children under age 5 years whose birth was registered with the civil authority (%)',
       ...
       'Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       'Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)',
       'Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)',
       'Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)',
       'Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)',
       'Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)',
       'Women age 15 years and above who use any kind of tobacco (%)',
       'Men age 15 years and above who use any kind of tobacco (%)',
       'Women age 15 years and above who consume alcohol (%)',
       'Men age 15 years and above who consume alcohol (%)'],
      dtype='object', length=109)

In [2]:
# Selecting Relevant Columns

anemia_df = df[
[
    'District Names',
    'State/UT',
    'Women (age 15-49) who are literate4 (%)',
    'Women (age 15-49)  with 10 or more years of schooling (%)',
    'Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)',
    'Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)',
    'Institutional births (in the 5 years before the survey) (%)',
    'Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)',
    'Population living in households that use an improved sanitation facility2 (%)',
    'Households using clean fuel for cooking3 (%)',
    'Households with any usual member covered under a health insurance/financing scheme (%)',
    'All women age 15-49 years who are anaemic22 (%)',
    'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)',
    'Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)',
    'Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)',
    'All women age 15-19 years who are anaemic22 (%) '
]]

print(anemia_df.shape)

display(anemia_df.head())

anemia_df.to_excel("AnemiaPrevalence_Selected_cols.xlsx", index=False)

(707, 16)

,District Names,State/UT,Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 15-19 years who were already mothers or pregnant at the time of the survey (%),Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%),Institutional births (in the 5 years before the survey) (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Population living in households that use an improved sanitation facility2 (%),Households using clean fuel for cooking3 (%),Households with any usual member covered under a health insurance/financing scheme (%),All women age 15-49 years who are anaemic22 (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%),All women age 15-19 years who are anaemic22 (%)
0,Nicobars,Andaman & Nicobar Islands,87.5,53.5,1.8,72.6,97.8,8.2,83.5,56.9,2.7,38.3,37.7,38.4,*,48.0
1,North & Middle Andaman,Andaman & Nicobar Islands,84.0,41.0,3.8,83.7,97.7,8.6,86.4,61.3,2.1,62.1,30.4,62.5,*,47.8
2,South Andaman,Andaman & Nicobar Islands,86.7,57.5,2.8,81.0,99.5,10.0,89.3,91.9,1.2,57.7,43.4,57.6,*,43.2
3,Srikakulam,Andhra Pradesh,64.3,42.5,5.5,67.5,97.9,13.8,71.6,74.7,75.6,62.6,59.6,62.8,*,59.2
4,Vizianagaram,Andhra Pradesh,58.3,37.6,12.7,59.6,99.0,16.9,61.7,60.3,76.7,64.0,66.7,64.6,*,73.9

In [3]:
# Statical Summary of Selected columns
display(anemia_df.describe().T)

,count,mean,std,min,25%,50%,75%,max
Women (age 15-49) who are literate4 (%),707.0,74.350495,12.250455,38.6,66.85,75.1,83.75,99.7
Women (age 15-49) with 10 or more years of schooling (%),707.0,40.345403,14.224272,13.6,29.30,39.2,49.90,88.2
Institutional births (in the 5 years before the survey) (%),707.0,88.677935,12.003841,21.4,83.70,92.2,97.40,100.0
Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),707.0,17.881188,7.454082,1.2,12.65,18.0,23.10,43.6
Population living in households that use an improved sanitation facility2 (%),707.0,71.948515,14.287484,29.2,62.00,73.8,83.35,99.9
Households using clean fuel for cooking3 (%),707.0,54.127016,24.165069,8.6,34.00,50.6,75.15,99.8
Households with any usual member covered under a health insurance/financing scheme (%),707.0,40.176096,23.103115,1.2,20.20,35.7,59.95,97.8
All women age 15-49 years who are anaemic22 (%),707.0,55.892362,11.955941,14.9,49.15,57.2,63.60,93.5
Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),707.0,56.137199,12.028755,15.6,49.35,57.5,63.80,94.6

**Filtering**

In [4]:
# Filter data for multiple specific states
target_states = ['West Bengal', 'Bihar', 'Assam']
states_df = anemia_df[anemia_df['State/UT'].isin(target_states)]

display(states_df[['District Names', 'State/UT', 'All women age 15-49 years who are anaemic22 (%)']])

,District Names,State/UT,All women age 15-49 years who are anaemic22 (%)
36,Kokrajhar,Assam,59.5
37,Goalpara,Assam,64.9
38,Barpeta,Assam,64.8
39,Morigaon,Assam,64.2
40,Lakhimpur,Assam,65.4
...,...,...,...
701,Kolkata,West Bengal,58.2
702,South Twenty Four Pargana,West Bengal,61.6
703,Paschim Medinipur,West Bengal,81.5
704,Purba Medinipur,West Bengal,70.4
705,Paschim Barddhaman,West Bengal,65.8

In [5]:
# Districts with high anemia AND low female literacy
filtered_df = anemia_df[
    (anemia_df['All women age 15-49 years who are anaemic22 (%)'] > 60) &
    (anemia_df['Women (age 15-49) who are literate4 (%)'] < 60)
]
display(filtered_df[['District Names', 'State/UT', 'All women age 15-49 years who are anaemic22 (%)', 'Women (age 15-49) who are literate4 (%)']])

,District Names,State/UT,All women age 15-49 years who are anaemic22 (%),Women (age 15-49) who are literate4 (%)
4,Vizianagaram,Andhra Pradesh,64.0,58.3
71,Sheohar,Bihar,61.6,52.5
72,Sitamarhi,Bihar,61.7,51.7
73,Madhubani,Bihar,61.4,53.2
74,Supaul,Bihar,60.7,42.1
75,Araria,Bihar,67.9,43.7
76,Kishanganj,Bihar,65.1,48.0
77,Purnia,Bihar,66.0,47.5
78,Katihar,Bihar,68.4,49.7
79,Madhepura,Bihar,65.7,47.6
80,Saharsa,Bihar,65.3,43.1
81,Darbhanga,Bihar,60.8,49.4
87,Samastipur,Bihar,60.5,54.3
91,Banka,Bihar,65.9,55.7
93,Lakhisarai,Bihar,72.6,57.9
94,Sheikhpura,Bihar,69.5,55.0
95,Nalanda,Bihar,71.0,56.1
102,Gaya,Bihar,64.3,59.4
104,Jamui,Bihar,75.2,48.7
118,Narayanpur,Chhattisgarh,72.0,53.8
119,Bijapur,Chhattisgarh,72.1,46.3
123,Bastar,Chhattisgarh,77.2,54.6
126,Dantewada,Chhattisgarh,76.0,50.3
129,Kodagaon,Chhattisgarh,79.7,56.1
132,Sukma,Chhattisgarh,78.4,40.5
148,Dohad,Gujarat,75.1,56.1
160,Chhota Udaipur,Gujarat,78.9,53.2
190,Mewat,Haryana,60.6,45.1
230,Giridih,Jharkhand,64.7,57.3
231,Deoghar,Jharkhand,70.2,54.2
232,Godda,Jharkhand,66.3,50.4
233,Sahibganj,Jharkhand,71.5,54.9
234,Pakur,Jharkhand,79.7,46.7
240,Latehar,Jharkhand,63.6,58.7
243,Dumka,Jharkhand,73.4,55.6
244,Jamtara,Jharkhand,77.7,57.4
246,Khunti,Jharkhand,70.0,59.9
249,Pashchimi Singhbhum,Jharkhand,72.6,49.8
255,Raichur,Karnataka,60.4,54.3
298,Sheopur,Madhya Pradesh,64.9,54.8
344,Alirajpur,Madhya Pradesh,60.5,42.1
349,Nandurbar,Maharastra,64.2,57.7
454,Gajapati,Odisha,66.1,50.5
459,Nuapada,Odisha,64.0,57.2
461,Rayagada,Odisha,69.1,45.1
462,Nabarangapur,Odisha,69.3,41.0
464,Malkangiri,Odisha,71.9,41.3
498,Dhaulpur,Rajasthan,68.5,59.9
499,Karauli,Rajasthan,61.5,54.8
520,Baran,Rajasthan,60.1,59.7
565,Jayashankar Bhupalapally,Telangana,65.9,58.9
566,Jogulamba Gadwal,Telangana,64.6,45.0
570,Komaram Bheem Asifabad,Telangana,67.3,51.7
571,Mahabubabad,Telangana,62.8,58.0
586,Vikarabad,Telangana,61.0,59.3
613,Bareilly,Uttar Pradesh,60.8,54.7
615,Shahjahanpur,Uttar Pradesh,60.3,59.5

In [6]:
# Top 10 High anemic States
state_anemia = anemia_df.groupby('State/UT')['All women age 15-49 years who are anaemic22 (%)'].mean().reset_index()

high_anemia_states = state_anemia.sort_values(by='All women age 15-49 years who are anaemic22 (%)', ascending=False)

display(high_anemia_states.head(10))

           State/UT  All women age 15-49 years who are anaemic22 (%)
17           Ladakh                                        92.750000
35      West Bengal                                        71.526316
32          Tripura                                        67.050000
13  Jammu & Kashmir                                        66.930000
14        Jharkhand                                        66.275000
4             Assam                                        65.745455
5             Bihar                                        64.684211
10          Gujarat                                        64.569697
25           Odisha                                        64.303333
7      Chhattisgarh                                        63.011111

In [7]:
#Caluculation of Top 5% Anemic Districts
# Calculate the threshold for the 95th percentile of anemia
threshold = anemia_df['All women age 15-49 years who are anaemic22 (%)'].quantile(0.95)

# Filter districts above this threshold
top_5_percent = anemia_df[anemia_df['All women age 15-49 years who are anaemic22 (%)'] >= threshold].sort_values(by='All women age 15-49 years who are anaemic22 (%)', ascending=False)
display(top_5_percent[['District Names', 'State/UT', 'All women age 15-49 years who are anaemic22 (%)']])

,District Names,State/UT,All women age 15-49 years who are anaemic22 (%)
295,Leh(Ladakh),Ladakh,93.5
296,Kargil,Ladakh,92.0
222,Kishtwar,Jammu & Kashmir,84.8
197,Lahul & Spiti,Himachal Pradesh,82.1
691,Dakshin Dinajpur,West Bengal,82.0
703,Paschim Medinipur,West Bengal,81.5
56,Udalguri,Assam,81.5
234,Pakur,Jharkhand,79.7
129,Kodagaon,Chhattisgarh,79.7
160,Chhota Udaipur,Gujarat,78.9
132,Sukma,Chhattisgarh,78.4
694,Birbhum,West Bengal,77.7
244,Jamtara,Jharkhand,77.7
693,Murshidabad,West Bengal,77.6
155,Tapi,Gujarat,77.4
157,Aravali,Gujarat,77.3
151,The Dangs,Gujarat,77.2
215,Ganderbal,Jammu & Kashmir,77.2
44,Golaghat,Assam,77.2
123,Bastar,Chhattisgarh,77.2
219,Kulgam,Jammu & Kashmir,77.0
698,Bankura,West Bengal,77.0
699,Puruliya,West Bengal,76.7
165,Kheda,Gujarat,76.1
126,Dantewada,Chhattisgarh,76.0
149,Narmada,Gujarat,75.9
449,Anugul,Odisha,75.8
153,Valsad,Gujarat,75.7
104,Jamui,Bihar,75.2
148,Dohad,Gujarat,75.1
697,Hugli,West Bengal,75.1
689,Koch Bihar,West Bengal,74.8
52,Kamrup Metropolitan,Assam,74.6
218,Anantnag,Jammu & Kashmir,74.3
208,Badgam,Jammu & Kashmir,73.9
213,Bandipore,Jammu & Kashmir,73.7